
//! Autogenerated weights for substratekitties
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-05-18, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// target/release/substratekitties
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=substratekitties
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./runtime/src/weights.rs


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for substratekitties.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> substratekitties::WeightInfo for WeightInfo<T> {
	fn sort_vector(x: u32, ) -> Weight {
		(779_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(x as Weight))
	}
}
